name: Lint Dockerfile
on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Dockerfile
        uses: actions/checkout@v2
      - name: Dockder
        run: curl -fsSL https://get.docker.com -o get-docker.sh 
          sh get-docker.sh
      - name: Hadolint 
        run: docker run --rm -v "$(PWD):/data" -w "/data" hadolint/hadolint hadolint Dockerfile
        