name: Lint Dockerfile
on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Dockerfile
        uses: actions/checkout@v2
      - name: Dockder
        run: curl -fsSL https://get.docker.com -o get-docker.sh 
          sh get-docker.sh
      - name: Hadolint 
        run: if docker run --rm -i hadolint/hadolint < Dockerfile
          | sed -re 's|^/dev/stdin:([0-9]*)|%d/%f:\1:WARNING:|'
          | grep -EC100 ':WARNING:' ; then exit 1 ; else exit 0 ; fi
        