name: CI test
on: push

jobs:
  testUnit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: composer install
      - name: Run test unit
        run: make test_unit
